/* -----------------------------------------------------------------------------
 * javascriptruntime.swg
 *
 * Javascript support code
 * ----------------------------------------------------------------------------- */

%insert(runtime) %{
#include "bindings/jswrapper/SeApi.h"
#include "bindings/bindings/manual/jsb_conversions.h" %}

//cjh %insert(runtime) "swigrun.swg";         /* SWIG API */
//cjh %insert(runtime) "swigerrors.swg";      /* SWIG errors */

//cjh %insert(runtime) "javascriptrun.swg";      /* SWIG errors */
